//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 09:18:56 AM CET 
//


package de.wildsau.dogtrailing.importer.tcx;

import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Root;

import java.util.ArrayList;
import java.util.List;


@Root
public class ActivityListT {

    @ElementList(name = "Activity", required = false, type = ActivityT.class, inline = true)
    protected List<ActivityT> activity;
    @ElementList(name = "MultiSportSession", required = false, type = MultiSportSessionT.class, inline = true)
    protected List<MultiSportSessionT> multiSportSession;

    public List<ActivityT> getActivity() {
        if (activity == null) {
            activity = new ArrayList<ActivityT>();
        }
        return this.activity;
    }

    public List<MultiSportSessionT> getMultiSportSession() {
        if (multiSportSession == null) {
            multiSportSession = new ArrayList<MultiSportSessionT>();
        }
        return this.multiSportSession;
    }

}
