//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 09:18:56 AM CET 
//


package de.wildsau.dogtrailing.importer.tcx;


import org.simpleframework.xml.Element;

public class PositionT {

    @Element(name = "LatitudeDegrees")
    protected double latitudeDegrees;
    @Element(name = "LongitudeDegrees")
    protected double longitudeDegrees;

    /**
     * Gets the value of the latitudeDegrees property.
     */
    public double getLatitudeDegrees() {
        return latitudeDegrees;
    }

    /**
     * Sets the value of the latitudeDegrees property.
     */
    public void setLatitudeDegrees(double value) {
        this.latitudeDegrees = value;
    }

    /**
     * Gets the value of the longitudeDegrees property.
     */
    public double getLongitudeDegrees() {
        return longitudeDegrees;
    }

    /**
     * Sets the value of the longitudeDegrees property.
     */
    public void setLongitudeDegrees(double value) {
        this.longitudeDegrees = value;
    }
}
