//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 09:18:56 AM CET 
//


package de.wildsau.dogtrailing.importer.tcx;

import org.simpleframework.xml.Element;

import java.util.Date;


public class TrackpointT {

    @Element(name = "Time", required = true)
    protected Date time;
    @Element(name = "Position")
    protected PositionT position;
    @Element(name = "AltitudeMeters", required = false)
    protected Double altitudeMeters;
    @Element(name = "DistanceMeters", required = false)
    protected Double distanceMeters;

    public Date getTime() {
        return time;
    }

    public void setTime(Date value) {
        this.time = value;
    }

    public PositionT getPosition() {
        return position;
    }

    public void setPosition(PositionT value) {
        this.position = value;
    }

    public Double getAltitudeMeters() {
        return altitudeMeters;
    }

    public void setAltitudeMeters(Double value) {
        this.altitudeMeters = value;
    }

    public Double getDistanceMeters() {
        return distanceMeters;
    }

    public void setDistanceMeters(Double value) {
        this.distanceMeters = value;
    }

}
