//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 09:18:56 AM CET 
//


package de.wildsau.dogtrailing.importer.tcx;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;


@Root(name = "TrainingCenterDatabase")
public class TrainingCenterDatabaseT {

    @Element(name = "Activities", required = false)
    protected ActivityListT activities;

    /**
     * Gets the value of the activities property.
     *
     * @return possible object is
     * {@link ActivityListT }
     */
    public ActivityListT getActivities() {
        return activities;
    }

    /**
     * Sets the value of the activities property.
     *
     * @param value allowed object is
     *              {@link ActivityListT }
     */
    public void setActivities(ActivityListT value) {
        this.activities = value;
    }
}
