package de.wildsau.dogtrailing.entities;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trailingSessionDaoConfig;

    private final TrailingSessionDao trailingSessionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trailingSessionDaoConfig = daoConfigMap.get(TrailingSessionDao.class).clone();
        trailingSessionDaoConfig.initIdentityScope(type);

        trailingSessionDao = new TrailingSessionDao(trailingSessionDaoConfig, this);

        registerDao(TrailingSession.class, trailingSessionDao);
    }

    public void clear() {
        trailingSessionDaoConfig.getIdentityScope().clear();
    }

    public TrailingSessionDao getTrailingSessionDao() {
        return trailingSessionDao;
    }

}
